### ISSUE TITLE
Pentaho plugin instalation problems

### ISSUE THREAD

**Issue by aabadi** [stratebi/STPivot4#1]
Is there any guide how to proceed to install it as plugin on  a pentaho CE ?

Thks in advance!

**Comment by stratebi** [comment]
aabadi, there is no guide at this moment (we are working on it). But, for installing as a plugin you have to compile the source code and copy the generated .zip (also generates a .tar.gz) file to the pentaho-solutions/system folder, and restart pentaho.

**Comment by aabadi** [comment]
Thank you very much for the help. pentaho has changed there repo. Therefore in order to work I needed to change 2 pom.xml to apply to the new urls.
Now it is working..
Thks a lot!

**Comment by stratebi** [comment]
Thanks to you aabadi, you can make a change request, to update the .pom files properly.

**Comment by bhericher** [comment]
The updated pom files would be usefull. Thank you!

**Comment by DSantonastaso** [comment]
Hi!
I have the same problem:
Failed to execute goal on project stpivot4-pentaho: Could not resolve dependencies for project com.stratebi.stpivot4:stpivot4-pentaho:jar:1.0-SNAPSHOT: Failed to collect dependencies at com.stratebi.stpivot4:stpivot4-analytics:jar:classes:1.0-SNAPSHOT: Failed to read artifact descriptor for com.stratebi.stpivot4:stpivot4-analytics:jar:classes:1.0-SNAPSHOT: Could not transfer artifact com.stratebi.stpivot4:stpivot4-analytics:pom:1.0-SNAPSHOT from/to pentaho-third-party (http://repo.pentaho.org/artifactory/third-party/): Failed to transfer http://repo.pentaho.org/artifactory/third-party/com/stratebi/stpivot4/stpivot4-analytics/1.0-SNAPSHOT/stpivot4-analytics-1.0-SNAPSHOT.pom. Error code 503, Service Temporarily Unavailable -> [Help 1]

Can you update pom with correct url?
Thanks Daniele

**Comment by guidorival** [comment]
Did not work for me running version 5.4. It ask for some dependencies. Any suggestions?

This is the error (copied textually) :

Failed to execute goal on project stpivot4-analytics: Could not resolve dependencies for project com.stratebi.stpivot4:stpivot4-analytics:war:1.0-SNAPSHOT: The following artifacts could not be resolved: pentaho:pentaho-platform-core:jar:5.4.0.1-130, pentaho:pentaho-platform-api:jar:5.4.0.1-130: Could not find artifact pentaho:pentaho-platform-core:jar:5.4.0.1-130 in prime-repo (http://repository.primefaces.org) -> [Help 1]

Any help would be much appreciated!

**Comment by aabadi** [comment]
Guys,
Sorry for the delay, I was on holidays... I have created 2 new pull request in order to change this repository.

The problem is that the url on the pom.xml for the pentaho repository doesnt exists... That why I did 2 changes.

The 2 changes I've done are:
file: stpivot4/pom.xml - Line 433 **NEW URL:** [](http://nexus.pentaho.org/content/repositories/)
file: stpivot4/stpivot4-pentaho/pom.xml - Line 398 **NEW URL**: [](http://nexus.pentaho.org/content/repositories/proxy-public-6.1-release)

Hope this will help you with the installation!
Rgds

**Comment by guidorival** [comment]
Aabadi, did you know any repositorie for pentaho 5.4.0.1-130 version ?
In nexus only exist 5.4.SNAPSHOT and didn't work

Thank you so much.

**Comment by aabadi** [comment]
Im sorry.. I dont know... Ive been trying a lot till I found that link (and worked for me).. 

Unfortunately I cant help you this time :( 

Rgds

**Comment by bhericher** [comment]
Hi, even with the 2 pom.xml updated (thank you aabadi), the build is failing for "STPivot4 Pentaho" : 
"Failed to execute goal on project stpivot4-pentaho: Could not resolve dependencies for project com.stratebi.stpivot4:stpivot4-pentaho:jar:1.0-SNAPSHOT: The following artifacts could not be resolved: pentaho:pentaho-platform-extensions:jar:6.1-SNAPSHOT" and many others...

**Comment by DSantonastaso** [comment]
Yesterday i was succeded compile project. If you want i can send compiled plugin.
Bye
Daniele

**Comment by bhericher** [comment]
Hi Daniele,
Thank you for your proposition. Maybe you could push the plugin on this repository
Benoit

**Comment by DSantonastaso** [comment]
Hi Benoit,
I guess i haven't right for upload file (or i not able).
Can you explain me?
Daniele

**Comment by DSantonastaso** [comment]
Hi,
today is possible to compile project without error
Daniele

**Comment by bhericher** [comment]
And today its fails...
Sorry guys, but I give up. Too bad, that looked very interesting.

**Comment by stratebi** [comment]
Hi all, thank you for the interest in the STPivot4,

Unfortunately pentaho is changing their repositories too fast, we are not able to track that changes as fast as they do. 
This is a weakness, we have our private repository with the pentaho resources, but it is in our local network.

We are going to update the poms files soon. 

For those who are interested in the compiled version only, we are available to help you, contact us.

Thanks,

**Comment by mcastillob** [comment]
Hi,

In org.pivot4j.ui.command.UICommandParameters have replaced the setCellOrdinal / getCellOrdinal methods with setCellCoordinate / getCellCoordinate which is probing problems
It's ViewHandlerPivot4j / PivotComponentBuilder.

I've patched my version for the moment, changing the int type to an array

https://github.com/mysticfall/pivot4j/commit/d6383072258de8cf1733efcdb87e7062195bd1ff

**Comment by stratebi** [comment]
Hi all, 

We have included new **working** repositories to solve the compilation problems and also made the changes int the code as suggested @mcastillob.

It **works** now.

We close the issue with this

Thanks,
