### ISSUE TITLE
Plugin doesn't work with Pentaho 8

### ISSUE THREAD

**Issue by juancash** [stratebi/STPivot4#9]
Hi,
the Plugin doesn't work with Pentaho 8. It's possible resolve this?
Thanks.

**Comment by mcastillob** [comment]
Hi ,
you can download the plugin in the following url https://github.com/stratebi/STPivot4/releases/download/v1.0.0-7.1/stpivot4-pentaho-1.0-SNAPSHOT-plugin.zip and unzip in  \pentaho-server\pentaho-solutions\system

then restart  pentaho server. 


it worked in my case on pentaho 8.0

**Comment by juancash** [comment]
@mcastillob 
Thank you very much for the link! I tried the plugin on my Pentaho 8 and doesn't work.
After realize a lot of tests I found the problem. STPivot and Pivot4J are not compatible. You only
can have one of them installed but not both at the same time. Thanks for your help!

**Comment by mcastillob** [comment]
@juancash
stpivot is a modified pivot4j. that's probably the problem is like having the same plugin twice

**Comment by juancash** [comment]
Perfect. Thanks.
